/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_leticia;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 1886519
 */
public class UpdateUserUI extends javax.swing.JFrame {

    int address;
    Connection con;
    CustomerDAO dao;
    int cid;
    String nome;
    String sobrenome;
    String email;
    int active;
    int loja;

    /**
     * Creates new form AddUserUI
     */
    public UpdateUserUI(int id, String fn, String ln, String em, int adr, int act, int loj) throws SQLException {
        cid = id;
        nome = fn;
        sobrenome = ln;
        email = em;
        address = adr;
        active = act;
        loja = loj;
        this.dao = new CustomerDAO();
        this.con = new ConnectionFactory().getConnection();
        
        initComponents();
        nomeTextField.setText(nome);
        sobrenomeTextField.setText(sobrenome);
        emailTextField.setText(email);
        lojaComboBox.setSelectedItem(loja);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lojaComboBox = new javax.swing.JComboBox<>();
        atualizarButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        endereçoLabel = new javax.swing.JLabel();
        endereçoTextField = new javax.swing.JTextField();
        nomeLabel1 = new javax.swing.JLabel();
        sobrenomeTextField = new javax.swing.JTextField();
        ativoSimRadio = new javax.swing.JRadioButton();
        ativoNaoRadio = new javax.swing.JRadioButton();
        ativoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(105, 95, 168));

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        tituloLabel.setBackground(new java.awt.Color(255, 0, 153));
        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caneta-do-usuario.png"))); // NOI18N
        tituloLabel.setText("Atualizar Dados");

        nomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nomeLabel.setText("Nome:");

        nomeTextField.setText(" ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Loja");

        lojaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        atualizarButton.setBackground(new java.awt.Color(255, 0, 153));
        atualizarButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        atualizarButton.setText("Atualizar");
        atualizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarButtonMouseClicked(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLabel.setText("E-mail");

        endereçoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        endereçoLabel.setText("Endereço");

        endereçoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endereçoTextFieldActionPerformed(evt);
            }
        });

        nomeLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nomeLabel1.setText("Sobrenome:");

        buttonGroup2.add(ativoSimRadio);
        ativoSimRadio.setText("Sim");

        buttonGroup2.add(ativoNaoRadio);
        ativoNaoRadio.setText("Não");
        ativoNaoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativoNaoRadioActionPerformed(evt);
            }
        });

        ativoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ativoLabel.setText("Ativo?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nomeLabel)
                                .addGap(15, 15, 15))
                            .addComponent(nomeLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sobrenomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailLabel)
                                    .addComponent(jLabel5))
                                .addGap(38, 38, 38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ativoLabel)
                                    .addComponent(endereçoLabel))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailTextField)
                                .addComponent(endereçoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lojaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(ativoSimRadio)
                                .addGap(63, 63, 63)
                                .addComponent(ativoNaoRadio)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sobrenomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lojaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endereçoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(endereçoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ativoSimRadio)
                    .addComponent(ativoNaoRadio)
                    .addComponent(ativoLabel))
                .addGap(18, 18, 18)
                .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 153));
        jPanel2.setFocusable(false);

        homeButton.setBackground(new java.awt.Color(105, 95, 168));
        homeButton.setForeground(new java.awt.Color(105, 95, 168));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casa.png"))); // NOI18N
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(homeButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(homeButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarButtonMouseClicked
        if ( (nomeTextField.getText().equals("") || sobrenomeTextField.getText().equals(""))) {
            
            System.out.println("nome OK"); 
            JOptionPane.showMessageDialog(null, "Preencha os campos", "Erro:", 2);
        }else if(( emailTextField.getText().equals("") 
                || endereçoTextField.getText().equals(""))) {
                    System.out.println("final OK");
                    JOptionPane.showMessageDialog(null, "Preencha os campos", "Erro:", 2);
        }else if (ativoSimRadio.isSelected() == false && ativoNaoRadio.isSelected() == false) {
            System.out.println("ativo OK");
            JOptionPane.showMessageDialog(null, "Preencha os campos", "Erro:", 2);
        }else{
                    System.out.println("c OK");
            

            try {
                if (ativoSimRadio.isSelected())active =1; else active = 0;
                
                System.out.println("TRY OK");
                String sql = "update customer "
                + "set store_id=?, first_name=?, last_name=?, email=?, address_id=?, active=? "
                + "where customer_id=?";
                PreparedStatement pst;
                pst = con.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(lojaComboBox.getSelectedItem() + ""));
                pst.setString(2, nomeTextField.getText());
                pst.setString(3, sobrenomeTextField.getText());
                pst.setString(4, emailTextField.getText());
                pst.setInt(5, Integer.parseInt(endereçoTextField.getText()));
                pst.setInt(6, 1);
                pst.setInt(7, cid);
                pst.execute();
                pst.close();

                JOptionPane.showMessageDialog(null, "Atualizado com sucesso!", "Sucesso", 1);
            } catch (SQLException ex) {
                Logger.getLogger(UpdateUserUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
                
        
    }//GEN-LAST:event_atualizarButtonMouseClicked

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        setVisible(false);
    }//GEN-LAST:event_homeButtonMouseClicked

    private void ativoNaoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativoNaoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ativoNaoRadioActionPerformed

    private void endereçoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endereçoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endereçoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UpdateUserUI(0, "", "", "", 1, 1, 0).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UpdateUserUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ativoLabel;
    private javax.swing.JRadioButton ativoNaoRadio;
    private javax.swing.JRadioButton ativoSimRadio;
    private javax.swing.JButton atualizarButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel endereçoLabel;
    private javax.swing.JTextField endereçoTextField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> lojaComboBox;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel nomeLabel1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField sobrenomeTextField;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
